version: 2.1
orbs:
  architect: giantswarm/architect@5.11.1

workflows:
  build:
    jobs:
    - architect/push-to-app-catalog:
        name: package and push chart
        context: architect
        app_catalog: giantswarm-playground-catalog
        app_catalog_test: giantswarm-playground-test-catalog
        chart: kubectl-apply-job
        executor: app-build-suite
        skip_conftest_deprek8ion: true
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
