{{- define "kubectlApplyJob.rbac.tpl" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "applyJob.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "applyJob.annotations" . | nindent 4 }}
  labels:
    {{- include "applyJob.defaultLabels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions/status
  verbs:
  - update
{{- if eq (include "applyJob.podSecurityPolicy.enabled" .) "true" }}
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ template "applyJob.name" . }}
  verbs:
  - use
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "applyJob.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "applyJob.annotations" . | nindent 4 }}
  labels:
    {{- include "applyJob.defaultLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "applyJob.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "applyJob.name" . }}
    namespace: {{ .Release.Namespace | quote }}
---
{{ end }}
