{{- define "kubectlApplyJob.sa.tpl" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "applyJob.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "applyJob.annotations" . | nindent 4 }}
  labels:
    {{- include "applyJob.defaultLabels" . | nindent 4 }}
---
{{ end }}
